name: Typescript

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: lts/fermium
#         cache: npm
    - name: npm
      working-directory: ./client
      run: npm install
    - name: test
      working-directory: ./client
      run: tsc --noEmit
